# 1. Data Collection — SpaceX REST API

Independent reconstruction of the IBM Applied Data Science Capstone data-collection workflow. The original course uses the SpaceX REST API; this notebook also loads the archived course-era extract so the notebook remains reproducible offline.

In [1]:
import pandas as pd
from pathlib import Path
DATA=Path('../data/dataset_part_1.csv')
api_url='https://api.spacexdata.com/v4/launches/past'
print('API endpoint:', api_url)
raw=pd.read_csv(DATA)
raw.head()

API endpoint: https://api.spacexdata.com/v4/launches/past

   FlightNumber        Date BoosterVersion  ...   Longitude   Latitude Class
0             1  2010-06-04       Falcon 9  ...  -80.577366  28.561857     0
1             2  2012-05-22       Falcon 9  ...  -80.577366  28.561857     0
2             3  2013-03-01       Falcon 9  ...  -80.577366  28.561857     0
3             4  2013-09-29       Falcon 9  ... -120.610829  34.632093     0
4             5  2013-12-03       Falcon 9  ...  -80.577366  28.561857     0

[5 rows x 18 columns]

In [2]:
print('Rows:', len(raw))
print('Columns:', list(raw.columns))
raw.info()

Rows: 90
Columns: ['FlightNumber', 'Date', 'BoosterVersion', 'PayloadMass', 'Orbit', 'LaunchSite', 'Outcome', 'Flights', 'GridFins', 'Reused', 'Legs', 'LandingPad', 'Block', 'ReusedCount', 'Serial', 'Longitude', 'Latitude', 'Class']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   FlightNumber    90 non-null     int64
 1   Date            90 non-null     object
 2   BoosterVersion  90 non-null     object
 3   PayloadMass     90 non-null     float64
 4   Orbit           90 non-null     object
 5   LaunchSite      90 non-null     object
 6   Outcome         90 non-null     object
 7   Flights         90 non-null     int64
 8   GridFins        90 non-null     bool
 9   Reused          90 non-null     bool
 10  Legs            90 non-null     bool
 11  LandingPad      64 non-null     object
 12  Block           90 non-null     float64
 13  ReusedCount     90 non-null     int64
 14  Serial          90 non-null     object
 15  Longitude       90 non-null     float64
 16  Latitude        90 non-null     float64
 17  Class           90 non-null     int64
dtypes: bool(3), float64(4), int64(4), object(7)
memory usage: 10.9+ KB

In [3]:
# In the live course workflow, requests.get(api_url).json() is normalized into a dataframe.
# Here the archived extract is used to make the notebook deterministic.
data=raw.copy()
data['Date']=pd.to_datetime(data['Date'])
data.head(10)

   FlightNumber       Date BoosterVersion  ...   Longitude   Latitude Class
0             1 2010-06-04       Falcon 9  ...  -80.577366  28.561857     0
1             2 2012-05-22       Falcon 9  ...  -80.577366  28.561857     0
2             3 2013-03-01       Falcon 9  ...  -80.577366  28.561857     0
3             4 2013-09-29       Falcon 9  ... -120.610829  34.632093     0
4             5 2013-12-03       Falcon 9  ...  -80.577366  28.561857     0
5             6 2014-01-06       Falcon 9  ...  -80.577366  28.561857     0
6             7 2014-04-18       Falcon 9  ...  -80.577366  28.561857     1
7             8 2014-07-14       Falcon 9  ...  -80.577366  28.561857     1
8             9 2014-08-05       Falcon 9  ...  -80.577366  28.561857     0
9            10 2014-09-07       Falcon 9  ...  -80.577366  28.561857     0

[10 rows x 18 columns]

In [4]:
print('Date range:', data['Date'].min().date(), 'to', data['Date'].max().date())
print('Launch sites:', data['LaunchSite'].nunique())
print('Unique booster serials:', data['Serial'].nunique())

Date range: 2010-06-04 to 2020-11-05
Launch sites: 3
Unique booster serials: 53